name: Add Small Label
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add small label
        run: ./.github/scripts/label_small.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.number }}
